# Generated by Django 3.2.5 on 2021-11-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('contextualizacao', models.TextField(verbose_name='Contextualização')),
                ('descricao_atividade', models.TextField(verbose_name='Descrição da atividade')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
    ]
