# Generated by Django 3.2.5 on 2022-05-18 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disciplina', '0004_auto_20220430_2332'),
        ('PlanoAula', '0005_planoaula_conteudos'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoaula',
            name='avaliacao',
            field=models.TextField(default='', verbose_name='Critérios de avaliação'),
        ),
        migrations.AddField(
            model_name='planoaula',
            name='prog_descricao',
            field=models.TextField(default='', verbose_name='Descrição da programação'),
        ),
        migrations.AddField(
            model_name='planoaula',
            name='prog_linguagem',
            field=models.CharField(default='', max_length=200, verbose_name='Linguagem de programação'),
        ),
        migrations.AddField(
            model_name='planoaula',
            name='prog_link',
            field=models.TextField(blank=True, null=True, verbose_name='Links'),
        ),
        migrations.AddField(
            model_name='planoaula',
            name='robo_descricao',
            field=models.TextField(default='', verbose_name='Descrição do robô'),
        ),
        migrations.AddField(
            model_name='planoaula',
            name='robo_equipamento',
            field=models.CharField(default='', max_length=200, verbose_name='Equipamento'),
        ),
        migrations.AddField(
            model_name='planoaula',
            name='robo_link',
            field=models.TextField(blank=True, null=True, verbose_name='Links'),
        ),
        migrations.AlterField(
            model_name='planoaula',
            name='conteudos',
            field=models.ManyToManyField(to='Disciplina.Conteudo', verbose_name='Conteúdos'),
        ),
    ]
