# Generated by Django 3.2.5 on 2022-09-07 10:29

import PlanoAula.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0004_alter_usuario_avatar'),
        ('PlanoAula', '0008_auto_20220615_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoaula',
            name='prog_codigos',
            field=models.FileField(blank=True, null=True, upload_to=PlanoAula.models.user_directory_path, verbose_name='Códigos'),
        ),
        migrations.AlterField(
            model_name='planoaula',
            name='robo_link',
            field=models.TextField(blank=True, null=True, verbose_name='Links'),
        ),
        migrations.CreateModel(
            name='LikePlanoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano_aula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='PlanoAula.planoaula', verbose_name='Plano de aula')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Usuario.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
                'ordering': ['usuario'],
            },
        ),
        migrations.CreateModel(
            name='ExecucaoPlanoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano_aula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='PlanoAula.planoaula', verbose_name='Plano de aula')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Usuario.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Execução',
                'verbose_name_plural': 'Execuções',
                'ordering': ['usuario'],
            },
        ),
    ]
