# Generated by Django 3.2.5 on 2022-09-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanoAula', '0009_auto_20220907_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoaula',
            name='exec_fotos',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_execucao/<function user_directory_path at 0x7ff3358835e0>'),
        ),
        migrations.AddField(
            model_name='planoaula',
            name='exec_videos',
            field=models.ImageField(blank=True, null=True, upload_to='videos_execucao/<function user_directory_path at 0x7ff3358835e0>'),
        ),
        migrations.AddField(
            model_name='planoaula',
            name='robo_fotos',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_robo/<function user_directory_path at 0x7ff3358835e0>'),
        ),
        migrations.AddField(
            model_name='planoaula',
            name='robo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf_robo/<function user_directory_path at 0x7ff3358835e0>'),
        ),
        migrations.AddField(
            model_name='planoaula',
            name='robo_videos',
            field=models.ImageField(blank=True, null=True, upload_to='videos_robo/<function user_directory_path at 0x7ff3358835e0>'),
        ),
        migrations.AlterField(
            model_name='planoaula',
            name='prog_codigos',
            field=models.FileField(blank=True, null=True, upload_to='codigos/<function user_directory_path at 0x7ff3358835e0>', verbose_name='Códigos'),
        ),
    ]
