# Generated by Django 3.2.5 on 2023-03-20 17:51

import PlanoAula.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlanoAula', '0010_auto_20220908_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execucaoplanoaula',
            name='plano_aula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='execucoes', to='PlanoAula.planoaula', verbose_name='Plano de aula'),
        ),
        migrations.AlterField(
            model_name='likeplanoaula',
            name='plano_aula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='likes', to='PlanoAula.planoaula', verbose_name='Plano de aula'),
        ),
        migrations.AlterField(
            model_name='planoaula',
            name='exec_fotos',
            field=models.ImageField(blank=True, null=True, upload_to=PlanoAula.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='planoaula',
            name='exec_videos',
            field=models.ImageField(blank=True, null=True, upload_to=PlanoAula.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='planoaula',
            name='prog_codigos',
            field=models.FileField(blank=True, null=True, upload_to=PlanoAula.models.user_directory_path, verbose_name='Códigos'),
        ),
        migrations.AlterField(
            model_name='planoaula',
            name='robo_fotos',
            field=models.ImageField(blank=True, null=True, upload_to=PlanoAula.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='planoaula',
            name='robo_pdf',
            field=models.FileField(blank=True, null=True, upload_to=PlanoAula.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='planoaula',
            name='robo_videos',
            field=models.ImageField(blank=True, null=True, upload_to=PlanoAula.models.user_directory_path),
        ),
    ]
