# Generated by Django 3.2.5 on 2022-03-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disciplina', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sugestaoconteudo',
            options={'ordering': ['status'], 'verbose_name': 'Sugestão de Conteúdo', 'verbose_name_plural': 'Sugestões de Conteúdo'},
        ),
        migrations.AlterModelOptions(
            name='sugestaodisciplina',
            options={'ordering': ['status'], 'verbose_name': 'Sugestão de Disciplina', 'verbose_name_plural': 'Sugestões de Disciplina'},
        ),
        migrations.AddField(
            model_name='sugestaoconteudo',
            name='data',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Data de criação'),
        ),
        migrations.AddField(
            model_name='sugestaodisciplina',
            name='data',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Data de criação'),
        ),
    ]
