# Generated by Django 3.2.5 on 2022-01-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, default='profile-pic/default.jpeg', null=True, upload_to='profile-pic/', verbose_name='Imagem de perfil'),
        ),
    ]
