# Generated by Django 3.2.5 on 2023-04-04 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Disciplina', '0005_alter_conteudo_disciplina'),
        ('Usuario', '0004_alter_usuario_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interesses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Disciplina.disciplina', verbose_name='Disciplina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='interesses_usuario', to='Usuario.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Interesse',
                'verbose_name_plural': 'Interesses',
                'ordering': ['usuario', 'disciplina'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='interesses',
            field=models.ManyToManyField(through='Usuario.Interesses', to='Disciplina.Disciplina'),
        ),
    ]
