# Generated by Django 3.2.5 on 2024-01-17 12:44

import Acoes.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0005_auto_20230404_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('Evento', 'Evento'), ('Curso', 'Curso'), ('Palestra', 'Palestra')], default='Evento', max_length=8)),
                ('data_inicio', models.DateField(default=datetime.date(2024, 1, 17), verbose_name='Data de início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de fim')),
                ('local', models.CharField(blank=True, max_length=200, null=True, verbose_name='Local')),
                ('descrição', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Usuario.usuario', verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Ação',
                'verbose_name_plural': 'Ações',
                'ordering': ['-data_inicio', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midia', models.ImageField(blank=True, null=True, upload_to=Acoes.models.user_directory_path)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Acoes.acoes', verbose_name='Ação')),
            ],
            options={
                'verbose_name': 'Mídia',
                'verbose_name_plural': 'Mídias',
                'ordering': ['acao'],
            },
        ),
        migrations.CreateModel(
            name='MensagemAcoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('data', models.DateTimeField(default=datetime.date(2024, 1, 17), verbose_name='Data')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Acoes.acoes', verbose_name='Ação')),
                ('mensagem_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Acoes.mensagemacoes', verbose_name='Mensagem original')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Usuario.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['acao', '-data'],
            },
        ),
    ]
