# Generated by Django 3.2.5 on 2024-01-17 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Acoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acoes',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de início'),
        ),
    ]
