# Generated by Django 3.2.5 on 2024-01-17 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Acoes', '0003_auto_20240117_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acoes',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
