# Generated by Django 3.2.5 on 2024-01-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acoes', '0004_rename_descrição_acoes_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acoes',
            options={'ordering': ['-data_inicio', '-data_fim', 'titulo'], 'verbose_name': 'Ação', 'verbose_name_plural': 'Ações'},
        ),
        migrations.AddField(
            model_name='acoes',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Está ativo'),
        ),
    ]
