# Generated by Django 3.2.5 on 2024-01-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acoes', '0005_auto_20240118_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acoes',
            options={'ordering': ['-status', '-data_inicio', '-data_fim', 'titulo'], 'verbose_name': 'Ação', 'verbose_name_plural': 'Ações'},
        ),
        migrations.AddField(
            model_name='acoes',
            name='deletada',
            field=models.BooleanField(default=False, verbose_name='Deletado'),
        ),
        migrations.AlterField(
            model_name='acoes',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Está em execução'),
        ),
    ]
