# Generated by Django 3.2.5 on 2024-01-21 22:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acoes', '0006_auto_20240119_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagemacoes',
            options={'ordering': ['acao', 'mensagem_original__pk', '-data'], 'verbose_name': 'Mensagem', 'verbose_name_plural': 'Mensagens'},
        ),
        migrations.AddField(
            model_name='midia',
            name='data',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='mensagemacoes',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='mensagemacoes',
            name='mensagem_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Acoes.mensagemacoes', verbose_name='Mensagem original'),
        ),
        migrations.AlterField(
            model_name='midia',
            name='acao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='midias', to='Acoes.acoes', verbose_name='Ação'),
        ),
    ]
