# Generated by Django 3.2.5 on 2024-01-25 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Acoes', '0008_alter_midia_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='midia',
            options={'ordering': ['acao', 'data'], 'verbose_name': 'Mídia', 'verbose_name_plural': 'Mídias'},
        ),
    ]
