# Generated by Django 3.2.5 on 2023-07-05 23:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0005_auto_20230404_0028'),
        ('PlanoAula', '0011_auto_20230320_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aulas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.PositiveIntegerField(verbose_name='Índice')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cursos', to='PlanoAula.planoaula', verbose_name='Plano de aula')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['curso', 'indice'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('quantidade_aulas', models.PositiveIntegerField(verbose_name='Quantidade de aulas')),
                ('aulas', models.ManyToManyField(related_name='aulas', through='Curso.Aulas', to='PlanoAula.PlanoAula', verbose_name='Aulas')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Usuario.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['titulo'],
            },
        ),
        migrations.AddField(
            model_name='aulas',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cursos', to='Curso.curso', verbose_name='Curso'),
        ),
    ]
