# Generated by Django 3.2.5 on 2021-12-17 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PlanoAula', '0002_planoaula_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoaula',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
