# Generated by Django 3.2.5 on 2022-01-28 13:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_usuario_avatar'),
        ('PlanoAula', '0003_planoaula_data_criacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planoaula',
            options={'ordering': ['titulo'], 'verbose_name': 'Plano de aula', 'verbose_name_plural': 'Planos de aula'},
        ),
        migrations.AlterField(
            model_name='planoaula',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='planoaula',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Usuario.usuario', verbose_name='Responsável'),
        ),
    ]
