# Generated by Django 3.2.5 on 2022-05-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disciplina', '0004_auto_20220430_2332'),
        ('PlanoAula', '0004_auto_20220128_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoaula',
            name='conteudos',
            field=models.ManyToManyField(to='Disciplina.Conteudo', verbose_name='Conteudos'),
        ),
    ]
