# Generated by Django 3.2.5 on 2022-05-18 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanoAula', '0006_auto_20220518_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planoaula',
            name='robo_link',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='Links'),
        ),
    ]
