# Generated by Django 3.2.5 on 2022-06-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disciplina', '0005_alter_conteudo_disciplina'),
        ('PlanoAula', '0007_alter_planoaula_robo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planoaula',
            name='avaliacao',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Critérios de avaliação'),
        ),
        migrations.AlterField(
            model_name='planoaula',
            name='conteudos',
            field=models.ManyToManyField(related_name='planos_de_aula', to='Disciplina.Conteudo', verbose_name='Conteúdos'),
        ),
        migrations.AlterField(
            model_name='planoaula',
            name='robo_link',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='Link'),
        ),
    ]
