# Generated by Django 3.2.5 on 2023-11-16 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlanoAula', '0011_auto_20230320_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planoaula',
            old_name='responsavel',
            new_name='criador',
        ),
    ]
