# Generated by Django 3.2.5 on 2024-01-25 00:47

import PlanoAula.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlanoAula', '0012_rename_responsavel_planoaula_criador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planoaula',
            name='exec_fotos',
        ),
        migrations.RemoveField(
            model_name='planoaula',
            name='exec_videos',
        ),
        migrations.RemoveField(
            model_name='planoaula',
            name='robo_fotos',
        ),
        migrations.RemoveField(
            model_name='planoaula',
            name='robo_videos',
        ),
        migrations.CreateModel(
            name='VideoRobo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execucao_video', models.ImageField(blank=True, null=True, upload_to=PlanoAula.models.user_directory_path)),
                ('plano_aula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='videos_execucao', to='PlanoAula.planoaula', verbose_name='Plano de aula')),
            ],
            options={
                'verbose_name': 'Vídeo da execução',
                'verbose_name_plural': 'Vídeos da execução',
                'ordering': ['-plano_aula__data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='FotoRobo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robo_foto', models.ImageField(blank=True, null=True, upload_to=PlanoAula.models.user_directory_path)),
                ('plano_aula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='fotos_robo', to='PlanoAula.planoaula', verbose_name='Plano de aula')),
            ],
            options={
                'verbose_name': 'Foto do robô',
                'verbose_name_plural': 'Fotos do robô',
                'ordering': ['-plano_aula__data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='FotoExecução',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execucao_foto', models.ImageField(blank=True, null=True, upload_to=PlanoAula.models.user_directory_path)),
                ('plano_aula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='fotos_execucao', to='PlanoAula.planoaula', verbose_name='Plano de aula')),
            ],
            options={
                'verbose_name': 'Foto da execução',
                'verbose_name_plural': 'Fotos da execução',
                'ordering': ['-plano_aula__data_criacao'],
            },
        ),
    ]
