# Generated by Django 3.2.5 on 2024-01-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanoAula', '0015_auto_20240129_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planoaula',
            name='avaliacao',
            field=models.TextField(blank=True, null=True, verbose_name='Critérios de avaliação'),
        ),
        migrations.AlterField(
            model_name='planoaula',
            name='prog_descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição da programação'),
        ),
        migrations.AlterField(
            model_name='planoaula',
            name='prog_linguagem',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Linguagem de programação'),
        ),
        migrations.AlterField(
            model_name='planoaula',
            name='robo_descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do robô'),
        ),
        migrations.AlterField(
            model_name='planoaula',
            name='robo_equipamento',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Equipamento'),
        ),
    ]
