# Generated by Django 3.2.5 on 2024-01-29 23:15

import PlanoAula.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanoAula', '0017_alter_videorobo_robo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoexecucao',
            name='execucao_video',
            field=models.FileField(blank=True, null=True, upload_to=PlanoAula.models.diretorio_plano_aula_midias, verbose_name='Vídeos da execução da atividade'),
        ),
        migrations.AlterField(
            model_name='videorobo',
            name='robo_video',
            field=models.FileField(blank=True, null=True, upload_to=PlanoAula.models.diretorio_plano_aula_midias, verbose_name='Vídeos do robô'),
        ),
    ]
