# Generated by Django 3.2.5 on 2022-04-29 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Disciplina', '0002_auto_20220310_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conteudo',
            options={'ordering': ['disciplina', 'nome'], 'verbose_name': 'Conteúdo', 'verbose_name_plural': 'Conteúdos'},
        ),
    ]
